# Default values for php-sql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  php: 
    name: hitman001/php-mysql
    tag: "v6"
  mysql: 
    name: mysql
    tag: "8.0"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.


service:
  php:
    type: LoadBalancer
    port: 80
  mysql:
    type: ClusterIP
    port: 3306

mountpath:
  mysql: /var/lib/mysql   #PVC will be mounted here

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:         # limits are set on php webserver
   cpu: 100m
   memory: 100Mi
  requests:
   cpu: 100m
   memory: 100Mi

# autoscaling is done on php webserver
autoscaling:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  memorylimit: 80Mi 



