apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql8
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
      - image: "{{ .Values.image.mysql.name }}:{{ .Values.image.mysql.tag }}"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password       # the value of ROOT_PASSWORD is coming from secret "mysecret"
        - name: MYSQL_DATABASE
          value: my_db
        - name: MYSQL_USER
          value: db_user
        - name: MYSQL_PASSWORD
          value: mypass
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: {{ .Values.service.mysql.port }}
          name: mysql8
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: {{ .Values.mountpath.mysql }} 
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim        # Mysql data is stored in pvc
