apiVersion: v1
kind: Service
metadata:
  name: mysql8-service
  labels:
    app: mysql8
spec:
  type: {{ .Values.service.mysql.type }}
  ports:
  - port: {{ .Values.service.mysql.port }}
    protocol: TCP
  selector:
    app: mysql8