apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: {{ .Values.service.php.type }}
  ports:
  - port: {{ .Values.service.php.port }}
    nodePort: 30007
    protocol: TCP
  selector:
    app: apache